console.log(String(1))
console.log(String(NaN))
console.log(String(Infinity))
console.log(String(true))
console.log(String(false))

console.log((1).toString())
console.log((NaN).toString())
console.log((Infinity).toString())
console.log((true).toString())
console.log((false).toString())

console.log(1 + '')
console.log(NaN + '')
console.log(Infinity + '')
console.log(true + '')
console.log(false + '')